### PR TITLE
add node-selector to helm chart

### PR DESCRIPTION
**Pull request by jazark**
🛠 Helm Chart Enhancement
- Adds `nodeSelector` label to helm chart

🧪 How to Test
Deploy and Validate: Deploy the updated chart in a controlled environment. Validate all new functionalities. This change is non-breaking and backwards compatible.

Closes https://github.com/DependencyTrack/helm-charts/issues/40

### CODE REVIEW

**Comment by nscuro** [comment]
Thanks for the PR @jazark! Please sign-off your commit so the DCO check passes. If you click on *Details* next to the DCO check, it will provide instructions on what to do.

**Comment by jazark** [comment]
> Thanks for the PR @jazark! Please sign-off your commit so the DCO check passes. If you click on _Details_ next to the DCO check, it will provide instructions on what to do.

Done, thank you for the heads up!

**Review by NissesSenap — APPROVED** [review]
LGTM

**Review by nscuro — APPROVED** [review]
Thanks!

**Pull request merged**
