### PR TITLE
Support `ingressClassName`, ingress `tls`, and `extraObjects`

### PR DESCRIPTION
**Pull request by NissesSenap**
Solves #20

### CODE REVIEW

**Comment by NissesSenap** [comment]
FYI @nscuro , this is a simplification of https://github.com/DependencyTrack/helm-charts/issues/17.
It solves the same issue and I think it will be easier for the community to maintain in the long run, and I still think it's easy enough to use. Especially since it follows how other helm charts normally look.

**Comment by nscuro** [comment]
Thanks @NissesSenap, really like the simplicity! 

Even if we end up adding more options in the future (not sold on that), I think it's great to start with the minimum viable version proposed here.

Do you mind bumping the chart version to 0.2.0?

**Comment by NissesSenap** [comment]
Ahh, missed that one. Done
Do you want me to squash the commits as well @nscuro ?

**Review by nscuro — APPROVED** [review]
Thanks! 

No need to squash yourself, the repo has been set up to only allow squash merges.

**Pull request merged**
